# A list of registry ids of dimensions players cannot travel to at all.
disabledDimensions = ["minecraft:the_end"]
#
# Whether to push the player back or not when not meeting the requirements to access a dimension.
pushBackPlayer = false
#
# Message displayed when the player cannot access the dimension.
accessDeniedMessage = "Access Denied!"
#
# This is the list of Strings that form the message with the missing requirements. You can modify each part to translate it or change text, but mesculating their order or deleting an entry will break the functionality. If it happens, delete the config file.
#There will now be a list of the requirements in the order of Strings they appear.
#2. blocksBroken
#3. blocksPlaced
#4. xpLevel
#5. playerKills
#6. mobKills
#7. playTime
#8. itemKeys
#9. effects
#10. health
#11. deaths
#12. chance
#13. advancements
#14. ftbQuestIds
#15. jumps
#16. timesFished
requirementsMessageBuilder = ["You need to:", "Break another %missingBlocksBroken% blocks", "Place another %missingBlocksPlaced% blocks", "Get another %missingXpLevels% experience levels", "Kill another %missingPlayerKills% players", "Kill another %missingMobKills% mobs", "Play for another %missingPlayTime% seconds", "Have the items %missingItems%", "Have the effects %missingEffects%", "Have another %missingHealth% hearts", "Die another %missingDeaths% times", "Try again! You have a %chance% chance", "Complete the advancements %missingAdvancements%", "Complete the Quests %missingFtbQuests%", "Jump another %missingJumps% times", "Fish another %missingFishingCount% times", "to enter this dimension."]
