#Whether recoil animations are enabled
recoilEnabled = true
#Whether hand bobbing is disabled when holding a gun
bobbingDisabled = true
#Whether the hands use a custom animation for holding guns
customHoldAnim = true
#Whether boots should emit particles when used
bootEffects = true
#Allows aiming guns by holding right click
aimingDownSights = true
