["Kill Counter Config"]
	"Enable Kill Counter" = true
	#Maximum duration to maintain kill streak (e.g. killing spree, legendary) (in milliseconds)
	# Default: 180000
	# Range: 1 ~ 9223372036854775807
	"streak Kill Time" = 180000
	#Time window for quick kills (e.g. double kill, penta kill) (in milliseconds)
	# Default: 20000
	# Range: 1 ~ 9223372036854775807
	"quick Kill Time" = 20000
	#Enable blacklist or whitelist for entities that can trigger kill counter.
	#'true' means blacklist
	"Entity Blacklist Or WhiteList" = true
	#Blacklist for entities that can trigger kill counter.
	"Entity Blacklist" = ["minecraft:armor_stand", "minecraft:pig", "minecraft:cow", "minecraft:chicken", "minecraft:sheep", "minecraft:cod", "minecraft:salmon", "minecraft:bee", "minecraft:slime"]
	#Whitelist for entities that can trigger kill counter.
	"Entity Whitelist" = ["minecraft:player", "modC:monsterD"]

["Death Message Config"]
	"Enable Death Msg" = true
	#Enable blacklist or whitelist for entities that can trigger death message.
	#'true' means blacklist
	"Death Msg Blacklist Or WhiteList" = true
	#Blacklist for entities that can trigger death message.
	"Death Msg Blacklist" = ["minecraft:armor_stand", "minecraft:pig", "minecraft:cow", "minecraft:chicken", "minecraft:sheep", "minecraft:cod", "minecraft:salmon", "minecraft:bee", "minecraft:slime"]
	#Whitelist for entities that can trigger death message.
	"Death Msg Whitelist" = ["minecraft:player", "modC:monsterD"]
