<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
[Client]
	#Render centrifuge comb inventory on the block.
	renderCombsInCentrifuge = true
	#Render bees inside bee jars.
	renderBeesInJars = true
	#Stop bee nest helmets from making sounds.
	mutedBeeNestHelmet = false
	#Bees wear santa hats.
	alwaysChristmas = false
	#Bees never wear santa hats.
	neverChristmas = false
	#Render entities inside amber blocks.
	renderEntitiesInAmber = true
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
[Client]
	#Render centrifuge comb inventory on the block.
	renderCombsInCentrifuge = true
	#Render bees inside bee jars.
	renderBeesInJars = true
	#Stop bee nest helmets from making sounds.
	mutedBeeNestHelmet = false
	#Bees wear santa hats.
	alwaysChristmas = false
	#Bees never wear santa hats.
	neverChristmas = false
	#Render entities inside amber blocks.
	renderEntitiesInAmber = true
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
