#When a boss has no target, should it be cleared?
boss_clear_when_no_target = true
#Multiplier for boss attributes health.
# Default: 1.0
# Range: 0.0625 ~ 10.0
boss_attributes_multiplier_health = 1.0
#Multiplier for boss attributes damage.
# Default: 1.0
# Range: 0.0625 ~ 10.0
boss_attributes_multiplier_damage = 1.0
#Should the boss have no physics? Only for some bosses.
boss_no_physics = true
#Should the boss leave on day? Only for some bosses.
boss_leave_on_day = false
#Should all monsters be enhanced?
#If false, only specific monsters in this mod.
enhance_all_monster = false
#Multiplier for monster attributes health.
# Default: 1.0
# Range: 0.0625 ~ 100.0
monster_attributes_multiplier_health = 1.0
#Multiplier for monster attributes damage.
# Default: 1.0
# Range: 0.0625 ~ 100.0
monster_attributes_multiplier_damage = 1.0
#Should monsters spawn without light?
spawn_without_light = true
#Chance to spawn slime on zombie head.
# Default: 0.05
# Range: 0.0 ~ 1.0
chance_to_spawn_slime_on_zombie_head = 0.05
#Chance to spawn a monster.
# Default: 1.0
# Range: 0.0 ~ 1.0
enemy_spawn_chance = 1.0
#Should the chance to spawn a monster apply to all monsters?
enemy_spawn_chance_apply_all = false
